version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: myappdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpass
      # ports:
      #   - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db_net

  auth-service:
    build: ./auth-service
    container_name: auth_service
    restart: always
    env_file:
      - ./backend/.env
    command: ["gunicorn", "--bind", "0.0.0.0:5001", "run:app"]
    ports:
      - "5001:5001"
    networks:
      - backend_net
      - db_net

  backend:
    build: ./backend
    container_name: flask_backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - db_net
      - backend_net
    volumes:
      - ./backend:/app
      - ./backend/migrations:/app/migrations

  frontend:
    build: ./frontend
    container_name: vue_frontend
    restart: always
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "3000:80"
      - "3443:443"
    networks:
      - backend_net
      - frontend_net

volumes:
  mysql_data:

networks:
  db_net:
  backend_net:
  frontend_net: