version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: myappdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db_net

  backend:
    build: ./backend
    container_name: flask_backend
    environment:
      - FLASK_ENV= development
      # - FLASK_APP=app/app.py
      - FLASK_APP=app.app:create_app
      - FLASK_DEBUG=1
      - DB_HOST= mysql_db
      - DB_USER= myuser
      - DB_PASSWORD= mypassword
      - DB_NAME= escola_db
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - db_net
      - backend_net
    volumes:
      - ./backend:/app
      - ./backend/migrations:/app/migrations 

  frontend:
    build: ./frontend
    container_name: react_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    # volumes:
    #   - ./frontend/src:/app/src
    #   - ./frontend/public:/app/public
    #   - ./frontend/.env:/app/.env
    #   - /app/node_modules       # Garante que o node_modules usado seja o do container
    networks:
      - backend_net
      - frontend_net
    environment:
      - REACT_APP_API_URL=http://flask_backend:5000/api

volumes:
  mysql_data:

networks:
  db_net:
  backend_net:
  frontend_net: