version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: myappdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpass
      # ports:
      #   - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db_net

  backend:
    build: ./backend
    container_name: flask_backend

    # Carrega variáveis AWS_COGNITO_* e outras do arquivo .env do backend
    env_file:
      - ./backend/.env

    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - db_net
      - backend_net
    volumes:
      - ./backend:/app
      - ./backend/migrations:/app/migrations

  frontend:
    build: ./frontend
    container_name: vue_frontend

    # Carrega variáveis VITE_* do arquivo .env do frontend
    env_file:
      - ./frontend/.env

    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - backend_net
      - frontend_net

volumes:
  mysql_data:

networks:
  db_net:
  backend_net:
  frontend_net:
