"""Criação da tabela usuario

Revision ID: f0fc7a6d6181
Revises: 
Create Date: 2025-04-10 01:07:37.798272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0fc7a6d6181'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('ultimo_nome', sa.String(length=50), nullable=True),
    sa.Column('login', sa.String(length=16), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('data_nascimento', sa.String(length=10), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id_user_insert', sa.Integer(), nullable=False),
    sa.Column('id_userupdate', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('login')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
