#auth-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: auth-service-app:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        # ESTE BLOCO É O MAIS IMPORTANTE
        envFrom:
        - secretRef:
            name: backend-secrets
        - configMapRef:
            name: backend-config