# k8s/web-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: backend-app
        image: pfransozi/escola-devsecops:v1
        imagePullPolicy: Never
        command: ["/entrypoint.sh"]
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "mysql+mysqlconnector://myuser:mypassword@mysql-db/myappdb"
        envFrom:
        - secretRef:
            name: backend-secrets
        - configMapRef:
            name: backend-config
